spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blibliWeb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 200309
  data:
    ##Redis非关系形数据库配置
    redis:
      port: 6379
      host: 127.0.0.1
  servlet:
    # 配置servlet的multipart设置，用于文件上传
    multipart:
      # 启用multipart文件上传功能
      enabled: true
      # 设置单个文件的最大大小为10MBcdm
      max-file-size: 10MB
      # 设置整个HTTP请求的最大大小为10MB，适应单文件或多文件上传
      max-request-size: 10MB
##开启驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true
# 配置 MyBatis 控制台输出 SQL
logging:
  level:
    com.ligg.mapper: debug
# 七牛云配置
qiniu:
  access-key: 0G5LPij1PyBXrrcZg9YoDAbqjdSzMQT15Vv6d-9G
  secret-key: XQz2Uhqp_AxbIZiMuW8Xof8fJml39vgIRxfcnkXq
  bucket-name: uploadlwz
  domain: http://sncodwj9m.hn-bkt.clouddn.com #https://portal.qiniu.com/
